/* Generates dist/sw.js.

   This is the one place the single-file rule bends, and only just: the game is
   still one HTML file with no dependencies. A service worker simply cannot be
   registered from an inline script, a data: URI or a blob, so offline support
   is impossible without a real same-origin file next to it.

   What it buys: the game works with no network at all rather than depending on
   whatever the browser happened to keep, and a new build reliably replaces the
   old one instead of lingering in an HTTP cache.

   The cache name is a hash of the built index.html, so the build stays
   byte-for-byte reproducible (CI gates on that) while any real change to the
   game produces a new cache and evicts the old one. */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const TEMPLATE = `/* Generated by tools/make-sw.js. Do not edit; rebuild instead. */
var VERSION = '__VERSION__';
var CACHE = '__NAME__-' + VERSION;
var SHELL = './index.html';

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(['./', SHELL]); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        return k === CACHE ? null : caches.delete(k);
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

/* Cache first. The whole app is one file that only changes when a new build
   ships, so going to the network first would cost latency on every launch and
   buy nothing.

   Deliberately no skipWaiting(): a new version takes over the next time the
   app is opened, never in the middle of a game. */
self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req).then(function (hit) {
      return hit || fetch(req).catch(function () { return caches.match(SHELL); });
    })
  );
});
`;

function makeSw(distDir, name) {
  const html = fs.readFileSync(path.join(distDir, 'index.html'));
  const version = crypto.createHash('sha256').update(html).digest('hex').slice(0, 12);
  const out = TEMPLATE.split('__VERSION__').join(version).split('__NAME__').join(name);
  fs.writeFileSync(path.join(distDir, 'sw.js'), out);
  return version;
}

module.exports = { makeSw };
